name: Deploy frontend example

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  deploy:
    uses: RADOSTb24/cloud-native-cicd-template/.github/workflows/deploy-web-service.yml@master
    with:
      component_name: frontend
      deploy_mode: kubernetes
      image_name: example/frontend-service
      container_name: example-frontend
      release_name: frontend
      app_port: "3000"
      host_port: "3000"
      namespace_prod: example-prod
      namespace_dev: example-dev

      templates_repo: RADOSTb24/cloud-native-cicd-template
      templates_ref: v1
      templates_chart_path: helm/web-service

      values_files: |
        deploy/values.yaml
        deploy/values-${{ github.ref_name == 'main' && 'prod' || 'dev' }}.yaml

      docker_context: .
      dockerfile: ./Dockerfile
      test_command: npm test
      test_language: node
      node_version: "20"
      verify_rollout_name: frontend
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      CLOUDFLEET_ACCESS_TOKEN_ID: ${{ secrets.CLOUDFLEET_ACCESS_TOKEN_ID }}
      CLOUDFLEET_ACCESS_TOKEN_SECRET: ${{ secrets.CLOUDFLEET_ACCESS_TOKEN_SECRET }}
      CLOUDFLEET_ORGANIZATION_ID: ${{ secrets.CLOUDFLEET_ORGANIZATION_ID }}
      CLOUDFLEET_CLUSTER_ID: ${{ secrets.CLOUDFLEET_CLUSTER_ID }}
      BUILD_ARGS: ${{ secrets.BUILD_ARGS }}