name: Rollback frontend example

on:
  workflow_dispatch:
    inputs:
      revision:
        description: "Optional Helm revision"
        required: false
        default: ""
        type: string

jobs:
  rollback:
    uses: RADOSTb24/cloud-native-cicd-template/.github/workflows/rollback-web-service.yml@master
    with:
      component_name: frontend
      deploy_mode: kubernetes
      image_name: example/frontend-service
      container_name: example-frontend

      app_port: "3000"
      host_port: "3000"

      release_name: frontend
      namespace_prod: example-prod
      namespace_dev: example-dev

      verify_rollout_name: frontend
      revision: ${{ inputs.revision }}

      # Optional SSH-specific options (used when deploy_mode: ssh)
      # container_network: shared-net
      # container_volumes: "-v /var/log/frontend-service:/logs"
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}

      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}

      CLOUDFLEET_ACCESS_TOKEN_ID: ${{ secrets.CLOUDFLEET_ACCESS_TOKEN_ID }}
      CLOUDFLEET_ACCESS_TOKEN_SECRET: ${{ secrets.CLOUDFLEET_ACCESS_TOKEN_SECRET }}
      CLOUDFLEET_ORGANIZATION_ID: ${{ secrets.CLOUDFLEET_ORGANIZATION_ID }}
      CLOUDFLEET_CLUSTER_ID: ${{ secrets.CLOUDFLEET_CLUSTER_ID }}
